USE NPPES
DROP TABLE [dbo].[healthcare_facility_locations];
GO
CREATE TABLE [dbo].[healthcare_facility_locations] (
	[FACID] numeric,
	[NPI] numeric,
	[FACNAME] nvarchar(100) not null,
	[FAC_TYPE_CODE] nvarchar(50) not null,
	[FAC_FDR] nvarchar(50) not null,
	[LTC] nvarchar(50) not null,
	[CAPACITY] int not null,
	[ADDRESS] nvarchar(50) not null,
	[CITY] nvarchar(50) not null,
	[ZIP] int null,
	[ZIP9] int null,
	[FACADMIN] nvarchar(50) null,
	[CONTACT_EMAIL] nvarchar(50) null,
	[CONTACT_FAX] nvarchar(50) null,
	[CONTACT_PHONE_NUMBER] nvarchar(50) null,
	[COUNTY_CODE] nvarchar(50) not null,
	[COUNTY_NAME] nvarchar(50) not null,
	[DISTRICT_NUMBER] int null,
	[DISTRICT_NAME] nvarchar(50) not null,
	[ISFACMAIN] nvarchar(50) not null,
	[LICENSE_NUMBER] nvarchar(15) null,
	[BUSINESS_NAME] nvarchar(100) null,
	[INITIAL_LICENSE_DATE] date,
	[LICENSE_EFFECTIVE_DATE] date,
	[LICENSE_EXPIRATION_DATE] date,
	[ENTITY_TYPE_DESCRIPTION] nvarchar(50) null,
	[LATITUDE] float,
	[LONGITUDE] float,
	[LOCATION] nvarchar(50) not null,
	[OSHPD_ID] nvarchar(15) null,
	[STREETNUM] nvarchar(50) not null,
	[STREETNAME] nvarchar(50) not null,
	[CCLHO_CODE] nvarchar(50) not null,
	[CCLHO_NAME] nvarchar(50) not null,
	[FIPS_COUNTY_CODE] nvarchar(15) not null,
	[BIRTHING_FACILITY_FLAG] nvarchar(50) null,
	[TRAUMA_PED_CTR] nvarchar(50) null,
	[TRAUMA_CTR] nvarchar(50) null,
	[TYPE_OF_CARE] nvarchar(50) null,
	[CRITICAL_ACCESS_HOSPITAL] nvarchar(50) null
);
GO
